# PLLAY Enterprise Solution Google Cloud Platform Managed Services Deployment Configuration

---
provider: google-cloud
project_id: pllay-enterprise
region: us-west1

database:
  firestore:
    collection: game-data
    mode: native

  cloud_sql:
    instance_name: pllay-postgres
    database_version: POSTGRES_13
    tier: db-custom-4-15360

  memorystore:
    tier: basic
    memory_size_gb: 5

compute:
  cloud_functions:
    runtime: nodejs14
    memory: 256MB
    timeout: 30s

  gke:
    cluster_name: pllay-cluster
    node_pools:
      - name: default-pool
        machine_type: e2-standard-2
        initial_node_count: 3
        autoscaling:
          min_node_count: 1
          max_node_count: 5

game_servers:
  cloud_game_servers:
    cluster_name: pllay-game-cluster
    scaling_config:
      fleet_autoscaler_spec:
        policy:
          type: Webhook
          webhook:
            service: 
              name: game-autoscaler
              namespace: default
              path: scale
    
content_delivery:
  cloud_cdn:
    enabled: true

storage:
  cloud_storage:
    bucket_name: pllay-assets

analytics:
  pubsub:
    topic_name: pllay-data-stream

  bigquery:
    dataset_id: pllay_analytics

monitoring:
  cloud_monitoring:
    notification_channels:
      - email: alerts@pllay.com

security:
  cloud_armor:
    policy_name: pllay-waf-policy

  firebase_auth:
    project_id: pllay-auth

  kms:
    keyring: pllay-keyring
    cryptokey: pllay-key

networking:
  vpc:
    name: pllay-network
    subnets:
      - name: subnet-1
        region: us-west1
        range: 10.0.0.0/20

  load_balancing:
    name: pllay-lb
    type: EXTERNAL

api_management:
  cloud_endpoints:
    name: pllay-api
    target: pllay-backend

compliance:
  cloud_audit_logs:
    log_type: DATA_READ

  cloud_dlp:
    enabled: true

ci_cd:
  cloud_build:
    filename: cloudbuild.yaml

disaster_recovery:
  multi_region:
    enabled: true
    secondary_region: us-east1