runtime: nodejs14
env: standard

instance_class: F2

env_variables:
  NODE_ENV: 'production'

automatic_scaling:
  min_instances: 1
  max_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always