name: Deploy

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/staging'
      env:
        DEPLOY_KEY: ${{ secrets.STAGING_DEPLOY_KEY }}
        SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -o StrictHostKeyChecking=no scripts/deploy-staging.sh ubuntu@$SERVER_IP:/home/ubuntu/
        ssh -i deploy_key -o StrictHostKeyChecking=no ubuntu@$SERVER_IP 'bash /home/ubuntu/deploy-staging.sh'

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      env:
        DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
        SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -o StrictHostKeyChecking=no scripts/deploy-production.sh ubuntu@$SERVER_IP:/home/ubuntu/
        ssh -i deploy_key -o StrictHostKeyChecking=no ubuntu@$SERVER_IP 'bash /home/ubuntu/deploy-production.sh'